-- Create landing_page_content table for dynamic homepage content
CREATE TABLE public.landing_page_content (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  section_name text NOT NULL UNIQUE,
  content jsonb NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.landing_page_content ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Anyone can read active landing page content" 
ON public.landing_page_content 
FOR SELECT 
USING (is_active = true);

CREATE POLICY "Admins can manage landing page content" 
ON public.landing_page_content 
FOR ALL 
USING (is_admin_user())
WITH CHECK (is_admin_user());

-- Add trigger for automatic timestamp updates
CREATE TRIGGER update_landing_page_content_updated_at
BEFORE UPDATE ON public.landing_page_content
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert default content for existing sections
INSERT INTO public.landing_page_content (section_name, content) VALUES
('hero', '{
  "headline": "Standard Thought",
  "subheadline": "Building the foundation for transformative thinking",
  "ctaText": "Get Started",
  "ctaUrl": "/blog"
}'),
('value_props', '{
  "title": "The Blueprint",
  "subtitle": "Four pillars that rebuild everything",
  "props": [
    {
      "title": "UNLEARN",
      "description": "Call out survival patterns that aren''t serving you.",
      "highlight": "Step 1"
    },
    {
      "title": "REBUILD", 
      "description": "Design beliefs, systems, and identity from truth.",
      "highlight": "Step 2"
    },
    {
      "title": "STACK",
      "description": "Make money, gain power, build without burnout.",
      "highlight": "Step 3"
    },
    {
      "title": "TRANSCEND",
      "description": "Break generational loops for good. Live free. Die full.",
      "highlight": "Step 4"
    }
  ]
}'),
('social_proof', '{
  "metrics": [
    {
      "value": "10,000+",
      "label": "Builders Awakened"
    },
    {
      "value": "$2.3M+",
      "label": "Generated by Members"
    },
    {
      "value": "147",
      "label": "Cycles Broken"
    }
  ]
}');